exports.socketEvents = {
  TEST: 'test',
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  ERROR: 'error',
  PAIR_FAILED: 'pairFailed',
  PAIR_SUCCESS: 'pairSuccess',
  CUSTOMER_JOIN: 'customer_join',
  CUSTOMER_JOINED: 'customer_joined',
  AGENT_VIEW_CHAT: 'agent_view_chat',
  AGENT_JOIN: 'agent_join',
  AGENT_LEAVE: 'agent_leave',
  SEND_MESSAGE: 'send_message',
  RECEIVE_MESSAGE: 'receive_message',
  AGENT_JOINED: 'agent_joined',
  AGENT_LEFT: 'agent_left',
  AGENT_DENIED: 'agent_denied',
  MESSAGE_HISTORY: 'message_history',
};